// date localization for locale 'de'
// generated by Jörn Zaefferer using Java's java.util.SimpleDateFormat
Date.dayNames = ['sunnuntai', 'maanantai', 'tiistai', 'keskiviikko', 'torstai', 'perjantai', 'lauantai'];
Date.abbrDayNames = ['su', 'ma', 'ti', 'ke', 'to', 'pe', 'la'];
Date.monthNames = ['tammikuu', 'helmikuu', 'maaliskuu', 'huhtikuu', 'toukokuu', 'kesäkuu', 'heinäkuu', 'elokuu', 'syyskuu', 'lokakuu', 'marraskuu', 'joulukuu'];
Date.abbrMonthNames = ['T', 'H', 'M', 'H', 'T', 'K', 'H', 'E', 'S', 'L', 'M', 'J'];
